const SET_URL = 'SET_URL'
const SET_DISPLAY_URL = 'SET_DISPLAY_URL'
const SET_INPUT = 'SET_INPUT'
const SET_LOADING = 'SET_LOADING'
const PROXY_DOMAIN = 'localhost'
const PROXY_PORT = '3000'
const SEARCH = 'duckduckgo.com'

export {
  SET_URL,
  SET_DISPLAY_URL,
  SET_INPUT,
  SET_LOADING,
  PROXY_DOMAIN,
  PROXY_PORT,
  SEARCH
}
